# Enable C++ support
language: cpp

os: osx
  osx_image: xcode10.1
  env: CC='gcc-8' CXX='g++-8' PHYSICELL_CPP='g++-8' BREW='gcc@8'

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - cd PhysiCell-1.4.1
  - make

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
